version: "2"

services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./resell
    restart: always
    env_file:
      - ./resell/.env
    ports:
      - "80:80"
    networks:
      - snkrswallet

  server:
    build:
      dockerfile: Dockerfile
      context: ./resell-server
    restart: always
    ports:
      - "3000:3000"
    networks:
      - snkrswallet

networks:
  snkrswallet:
