name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Update server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.ACCESS_KEY }}
          script: cd /home/ec2-user/snkrswallet/resell-server && git pull https://alessandro-marcantoni:${{ secrets.ACCESS_TOKEN }}@github.com/alessandro-marcantoni/resell-server
      - name: Update client
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.ACCESS_KEY }}
          script: cd /home/ec2-user/snkrswallet/resell && git pull https://alessandro-marcantoni:${{ secrets.ACCESS_TOKEN }}@github.com/alessandro-marcantoni/resell
      - name: Delete docker containers and images
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.ACCESS_KEY }}
          script: docker stop snkrswallet_client_1 snkrswallet_server_1 && docker rm -f snkrswallet_client_1 snkrswallet_server_1 && docker rmi snkrswallet_client snkrswallet_server
      - name: Build new docker compose
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.ACCESS_KEY }}
          script: cd /home/ec2-user/snkrswallet && docker-compose up --detach
