name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Login SSH and Deploy
        run: |
          echo "${{ secrets.ACCESS_KEY }}" > private.key
          ssh -i private.key ec2-user@18.157.192.138
          cd /home/ec2-user/snkrswallet/resell-server
          git pull https://alessandro-marcantoni:${{ secrets.ACCESS_TOKEN }}@github.com/alessandro-marcantoni/resell-server
          cd /home/ec2-user/snkrswallet/resell
          git pull https://alessandro-marcantoni:${{ secrets.ACCESS_TOKEN }}@github.com/alessandro-marcantoni/resell
          cd /home/ec2-user/snkrswallet
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
          docker rmi $(docker images -a -q)
          docker-compose up
