name: Continuous Deployment

on:
  workflow_dispatch:
  push:
    branch:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    name: Deploy
    steps:
      - name: Checkout Code
        run: cd /home/ec2-user/snkrswallet
      - name: Update Server
        run: |
          cd ./resell-server
          git pull https://alessandro-marcantoni:${{ secrets.ACCESS_TOKEN }}@github.com/alessandro-marcantoni/resell-server
          cd ..
      - name: Update Client
        run: |
          cd ./resell
          git pull https://alessandro-marcantoni:${{ secrets.ACCESS_TOKEN }}@github.com/alessandro-marcantoni/resell
          cd ..
      - name: Remove existing containers
        run: |
          docker stop $(docker ps -aq)
          docker rm $(docker ps -aq)
      - name: Remove existing images
        run: docker rmi $(docker images -a -q)
      - name: Build new containers
        run: docker-compose up
